---
  - name: sudo apt-get update and install "python-pip" package
    apt: 
       name: python-pip 
       state: present 
       update_cache: yes
       cache_valid_time: 360000
    become: True

  - name: docker login 
    docker_login: 
      registry: "{{private_docker_repo}}"
      username: "{{docker_repo_user}}"
      password: "{{docker_repo_pass}}"
      reauthorize: yes
    # become: True

  - name: remove all images without at least one container associated to them
    command: docker image prune -a -f

#####deploy-container########
- name: pull docker images
  command: docker pull {{private_docker_repo}}/stable/{{git_project_name}}:{{image_tag}}

- name: Stop a container
  docker_container:
    name: "test-mall-{{git_project_name}}"
    state: absent
    stop_timeout: 25

- name: run docker_image
  docker_container:
    name: "test-mall-{{git_project_name}}"
    image: "{{private_docker_repo}}/stable/{{git_project_name}}:{{image_tag}}"
    network_mode: host
    published_ports:
      - "{{web_port}}:{{web_port}}"
      - "{{dubbo_port}}:{{dubbo_port}}"
    volumes:
      - "/tmp:/tmp"
      - "/home/dkongjian/logs/stable/{{git_project_name}}:/logs/stable/{{git_project_name}}"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"

- name: wait for port available
  wait_for: port={{ web_port }} delay=10 timeout=120
