---
- name: copy the Dockerfile file
  template: src=Dockerfile dest=/home/dkongjian/gitrepo/dev-stable-caclub/{{git_project_name}}/target/Dockerfile  owner=dkongjian group=dkongjian mode=0644
  become: True
