---

- name: pull docker images
  command: docker pull {{private_docker_repo}}/test-mall/{{git_project_name}}:{{image_tag}}

#- name: Stop a container
#  docker_container:
#    name: "caclub-{{git_project_name}}"
#    state: absent
#    stop_timeout: 25

- name: run docker_image
  docker_container:
    name: "caclub-{{git_project_name}}"
    image: "{{private_docker_repo}}/test-mall/{{git_project_name}}:{{image_tag}}"
    network_mode: host
    published_ports:
      - "{{web_port}}:{{web_port}}"
      - "{{dubbo_port}}:{{dubbo_port}}"
    volumes:
      - "/tmp:/tmp"
      - "/home/dkongjian/logs/test-mall/{{git_project_name}}:/logs/test-mall/{{git_project_name}}"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"

- name: wait for port available
  wait_for: port={{ web_port }} delay=10 timeout=120
